//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GcuClient.Wdr.ServiceReference;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class ErrorMessage
{
    
    private MessageHeader messageHeaderField;
    
    private MessageStatus messageStatusField;
    
    private AdministrativeContactInformation administrativeContactInformationField;
    
    private ErrorMessageErrorCauseReference errorCauseReferenceField;
    
    private ErrorMessageError[] errorField;
    
    private CompositIdentifierPlannedType[] plannedTransportIdentifiersField;
    
    private TransportOperationalIdentifiers[] transportOperationalIdentifiersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MessageHeader MessageHeader
    {
        get
        {
            return this.messageHeaderField;
        }
        set
        {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public MessageStatus MessageStatus
    {
        get
        {
            return this.messageStatusField;
        }
        set
        {
            this.messageStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public AdministrativeContactInformation AdministrativeContactInformation
    {
        get
        {
            return this.administrativeContactInformationField;
        }
        set
        {
            this.administrativeContactInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public ErrorMessageErrorCauseReference ErrorCauseReference
    {
        get
        {
            return this.errorCauseReferenceField;
        }
        set
        {
            this.errorCauseReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Error", Order=4)]
    public ErrorMessageError[] Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PlannedTransportIdentifiers", Order=5)]
    public CompositIdentifierPlannedType[] PlannedTransportIdentifiers
    {
        get
        {
            return this.plannedTransportIdentifiersField;
        }
        set
        {
            this.plannedTransportIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TransportOperationalIdentifiers", Order=6)]
    public TransportOperationalIdentifiers[] TransportOperationalIdentifiers
    {
        get
        {
            return this.transportOperationalIdentifiersField;
        }
        set
        {
            this.transportOperationalIdentifiersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class MessageHeader
{
    
    private MessageReference messageReferenceField;
    
    private string messageRoutingIDField;
    
    private string senderReferenceField;
    
    private Sender senderField;
    
    private System.DateTime messageDateTimeCreatedField;
    
    private bool messageDateTimeCreatedFieldSpecified;
    
    private Recipient recipientField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MessageReference MessageReference
    {
        get
        {
            return this.messageReferenceField;
        }
        set
        {
            this.messageReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string MessageRoutingID
    {
        get
        {
            return this.messageRoutingIDField;
        }
        set
        {
            this.messageRoutingIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SenderReference
    {
        get
        {
            return this.senderReferenceField;
        }
        set
        {
            this.senderReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public Sender Sender
    {
        get
        {
            return this.senderField;
        }
        set
        {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime MessageDateTimeCreated
    {
        get
        {
            return this.messageDateTimeCreatedField;
        }
        set
        {
            this.messageDateTimeCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MessageDateTimeCreatedSpecified
    {
        get
        {
            return this.messageDateTimeCreatedFieldSpecified;
        }
        set
        {
            this.messageDateTimeCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public Recipient Recipient
    {
        get
        {
            return this.recipientField;
        }
        set
        {
            this.recipientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class MessageReference
{
    
    private string messageTypeField;
    
    private string messageTypeVersionField;
    
    private string messageIdentifierField;
    
    private System.DateTime messageDateTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MessageType
    {
        get
        {
            return this.messageTypeField;
        }
        set
        {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MessageTypeVersion
    {
        get
        {
            return this.messageTypeVersionField;
        }
        set
        {
            this.messageTypeVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string MessageIdentifier
    {
        get
        {
            return this.messageIdentifierField;
        }
        set
        {
            this.messageIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime MessageDateTime
    {
        get
        {
            return this.messageDateTimeField;
        }
        set
        {
            this.messageDateTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public partial class CompositIdentifierOperationalType
{
    
    private ObjectType objectTypeField;
    
    private string companyField;
    
    private string coreField;
    
    private string variantField;
    
    private string timetableYearField;
    
    private System.DateTime startDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ObjectType ObjectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Core
    {
        get
        {
            return this.coreField;
        }
        set
        {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Variant
    {
        get
        {
            return this.variantField;
        }
        set
        {
            this.variantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string TimetableYear
    {
        get
        {
            return this.timetableYearField;
        }
        set
        {
            this.timetableYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum ObjectType
{
    
    /// <remarks/>
    TR,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    CR,
    
    /// <remarks/>
    PR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public partial class AddressInformation
{
    
    private string companyNameField;
    
    private string addressField;
    
    private string cityTownField;
    
    private CountryCodeISO countryCodeISOField;
    
    private string postalCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string CityTown
    {
        get
        {
            return this.cityTownField;
        }
        set
        {
            this.cityTownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public CountryCodeISO CountryCodeISO
    {
        get
        {
            return this.countryCodeISOField;
        }
        set
        {
            this.countryCodeISOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string PostalCode
    {
        get
        {
            return this.postalCodeField;
        }
        set
        {
            this.postalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class CountryCodeISO
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public partial class CompositIdentifierPlannedType
{
    
    private ObjectType objectTypeField;
    
    private string companyField;
    
    private string coreField;
    
    private string variantField;
    
    private string timetableYearField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ObjectType ObjectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Core
    {
        get
        {
            return this.coreField;
        }
        set
        {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Variant
    {
        get
        {
            return this.variantField;
        }
        set
        {
            this.variantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string TimetableYear
    {
        get
        {
            return this.timetableYearField;
        }
        set
        {
            this.timetableYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartDateSpecified
    {
        get
        {
            return this.startDateFieldSpecified;
        }
        set
        {
            this.startDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public partial class LocationIdent
{
    
    private CountryCodeISO countryCodeISOField;
    
    private string locationPrimaryCodeField;
    
    private string primaryLocationNameField;
    
    private LocationSubsidiaryIdentification locationSubsidiaryIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public CountryCodeISO CountryCodeISO
    {
        get
        {
            return this.countryCodeISOField;
        }
        set
        {
            this.countryCodeISOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
    public string LocationPrimaryCode
    {
        get
        {
            return this.locationPrimaryCodeField;
        }
        set
        {
            this.locationPrimaryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PrimaryLocationName
    {
        get
        {
            return this.primaryLocationNameField;
        }
        set
        {
            this.primaryLocationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public LocationSubsidiaryIdentification LocationSubsidiaryIdentification
    {
        get
        {
            return this.locationSubsidiaryIdentificationField;
        }
        set
        {
            this.locationSubsidiaryIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class LocationSubsidiaryIdentification
{
    
    private LocationSubsidiaryCode locationSubsidiaryCodeField;
    
    private string allocationCompanyField;
    
    private string locationSubsidiaryNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public LocationSubsidiaryCode LocationSubsidiaryCode
    {
        get
        {
            return this.locationSubsidiaryCodeField;
        }
        set
        {
            this.locationSubsidiaryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string AllocationCompany
    {
        get
        {
            return this.allocationCompanyField;
        }
        set
        {
            this.allocationCompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string LocationSubsidiaryName
    {
        get
        {
            return this.locationSubsidiaryNameField;
        }
        set
        {
            this.locationSubsidiaryNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class LocationSubsidiaryCode
{
    
    private LocationSubsidiaryCodeLocationSubsidiaryTypeCode locationSubsidiaryTypeCodeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public LocationSubsidiaryCodeLocationSubsidiaryTypeCode LocationSubsidiaryTypeCode
    {
        get
        {
            return this.locationSubsidiaryTypeCodeField;
        }
        set
        {
            this.locationSubsidiaryTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum LocationSubsidiaryCodeLocationSubsidiaryTypeCode
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("20")]
    Item20,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("26")]
    Item26,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("27")]
    Item27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("28")]
    Item28,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("29")]
    Item29,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("30")]
    Item30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("32")]
    Item32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("33")]
    Item33,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("34")]
    Item34,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("35")]
    Item35,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("36")]
    Item36,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("37")]
    Item37,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("38")]
    Item38,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("39")]
    Item39,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("40")]
    Item40,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("41")]
    Item41,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("42")]
    Item42,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("43")]
    Item43,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("44")]
    Item44,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("45")]
    Item45,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("46")]
    Item46,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("47")]
    Item47,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("48")]
    Item48,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("49")]
    Item49,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("50")]
    Item50,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("51")]
    Item51,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("52")]
    Item52,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("53")]
    Item53,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("54")]
    Item54,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("55")]
    Item55,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("56")]
    Item56,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("57")]
    Item57,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public partial class ConsignmentIdent
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class Sender
{
    
    private string cI_InstanceNumberField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="integer")]
    public string CI_InstanceNumber
    {
        get
        {
            return this.cI_InstanceNumberField;
        }
        set
        {
            this.cI_InstanceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class Recipient
{
    
    private string cI_InstanceNumberField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="integer")]
    public string CI_InstanceNumber
    {
        get
        {
            return this.cI_InstanceNumberField;
        }
        set
        {
            this.cI_InstanceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum MessageStatus
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class AdministrativeContactInformation
{
    
    private string nameField;
    
    private string eMailField;
    
    private string phoneNumberField;
    
    private string faxNumberField;
    
    private string freeTextFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string eMail
    {
        get
        {
            return this.eMailField;
        }
        set
        {
            this.eMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string FaxNumber
    {
        get
        {
            return this.faxNumberField;
        }
        set
        {
            this.faxNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string FreeTextField
    {
        get
        {
            return this.freeTextFieldField;
        }
        set
        {
            this.freeTextFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class ErrorMessageErrorCauseReference
{
    
    private MessageReference messageReferenceField;
    
    private string messageSenderReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MessageReference MessageReference
    {
        get
        {
            return this.messageReferenceField;
        }
        set
        {
            this.messageReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MessageSenderReference
    {
        get
        {
            return this.messageSenderReferenceField;
        }
        set
        {
            this.messageSenderReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class ErrorMessageError
{
    
    private string tagReferenceField;
    
    private ErrorMessageErrorTypeOfError typeOfErrorField;
    
    private ErrorMessageErrorSeverity severityField;
    
    private string errorCodeField;
    
    private string freeTextFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TagReference
    {
        get
        {
            return this.tagReferenceField;
        }
        set
        {
            this.tagReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ErrorMessageErrorTypeOfError TypeOfError
    {
        get
        {
            return this.typeOfErrorField;
        }
        set
        {
            this.typeOfErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ErrorMessageErrorSeverity Severity
    {
        get
        {
            return this.severityField;
        }
        set
        {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string FreeTextField
    {
        get
        {
            return this.freeTextFieldField;
        }
        set
        {
            this.freeTextFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum ErrorMessageErrorTypeOfError
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum ErrorMessageErrorSeverity
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class TransportOperationalIdentifiers : CompositIdentifierOperationalType
{
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://gcubroker.org/wdr", ConfigurationName="WdrEndpoint")]
public interface WdrEndpoint
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://gcubroker.org/wdr", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(ErrorMessage), Action="http://gcubroker.org/wdr", Name="ErrorMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CompositIdentifierOperationalType))]
    System.Threading.Tasks.Task<wdrResponse> wdrAsync(wdrRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class WagonDamageReportMessageContactUserRU
{
    
    private AdministrativeContactInformation administrativeContactInformationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AdministrativeContactInformation AdministrativeContactInformation
    {
        get
        {
            return this.administrativeContactInformationField;
        }
        set
        {
            this.administrativeContactInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class TransportInformation
{
    
    private ConsignmentIdent consignmentNumberField;
    
    private LocationIdent originField;
    
    private LocationIdent destinationField;
    
    private System.DateTime departureDateField;
    
    private LoadingStatus loadingStatusField;
    
    private TrainIdentifier trainIdentifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ConsignmentIdent ConsignmentNumber
    {
        get
        {
            return this.consignmentNumberField;
        }
        set
        {
            this.consignmentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public LocationIdent Origin
    {
        get
        {
            return this.originField;
        }
        set
        {
            this.originField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public LocationIdent Destination
    {
        get
        {
            return this.destinationField;
        }
        set
        {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
    public System.DateTime DepartureDate
    {
        get
        {
            return this.departureDateField;
        }
        set
        {
            this.departureDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public LoadingStatus LoadingStatus
    {
        get
        {
            return this.loadingStatusField;
        }
        set
        {
            this.loadingStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public TrainIdentifier TrainIdentifier
    {
        get
        {
            return this.trainIdentifierField;
        }
        set
        {
            this.trainIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum LoadingStatus
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class TrainIdentifier
{
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OperationalTrainNumber", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("TAF-Identifier", typeof(CompositIdentifierPlannedType), Order=0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class DamageDetection
{
    
    private LocationIdent locationField;
    
    private bool detectedUponHandoverField;
    
    private HandingOverCompany handingOverCompanyField;
    
    private System.DateTime detectionDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public LocationIdent Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool DetectedUponHandover
    {
        get
        {
            return this.detectedUponHandoverField;
        }
        set
        {
            this.detectedUponHandoverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public HandingOverCompany HandingOverCompany
    {
        get
        {
            return this.handingOverCompanyField;
        }
        set
        {
            this.handingOverCompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
    public System.DateTime DetectionDate
    {
        get
        {
            return this.detectionDateField;
        }
        set
        {
            this.detectionDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class HandingOverCompany
{
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private HandingOverCompanyCompanyType companyTypeField;
    
    private bool companyTypeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Company", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CompanyName", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HandingOverCompanyCompanyType CompanyType
    {
        get
        {
            return this.companyTypeField;
        }
        set
        {
            this.companyTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompanyTypeSpecified
    {
        get
        {
            return this.companyTypeFieldSpecified;
        }
        set
        {
            this.companyTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr", IncludeInSchema=false)]
public enum ItemChoiceType
{
    
    /// <remarks/>
    Company,
    
    /// <remarks/>
    CompanyName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum HandingOverCompanyCompanyType
{
    
    /// <remarks/>
    GCUsignatoryRU,
    
    /// <remarks/>
    NonGCUsignatoryRU,
    
    /// <remarks/>
    ConnectingRailway,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class ExistingLabels
{
    
    private LabelType[] damageLabelField;
    
    private ExistingLabelsReportingRU reportingRUField;
    
    private System.DateTime dateField;
    
    private bool dateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DamageLabel", Order=0)]
    public LabelType[] DamageLabel
    {
        get
        {
            return this.damageLabelField;
        }
        set
        {
            this.damageLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ExistingLabelsReportingRU ReportingRU
    {
        get
        {
            return this.reportingRUField;
        }
        set
        {
            this.reportingRUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
    public System.DateTime Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateSpecified
    {
        get
        {
            return this.dateFieldSpecified;
        }
        set
        {
            this.dateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public enum LabelType
{
    
    /// <remarks/>
    K,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    R1,
    
    /// <remarks/>
    U,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class ExistingLabelsReportingRU
{
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Company", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CompanyName", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr", IncludeInSchema=false)]
public enum ItemChoiceType1
{
    
    /// <remarks/>
    Company,
    
    /// <remarks/>
    CompanyName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class NewLabels
{
    
    private LabelType[] damageLabelField;
    
    private bool wagonDetachedField;
    
    private NewLabelsDispatchedToWorkshop dispatchedToWorkshopField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DamageLabel", Order=0)]
    public LabelType[] DamageLabel
    {
        get
        {
            return this.damageLabelField;
        }
        set
        {
            this.damageLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool WagonDetached
    {
        get
        {
            return this.wagonDetachedField;
        }
        set
        {
            this.wagonDetachedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public NewLabelsDispatchedToWorkshop DispatchedToWorkshop
    {
        get
        {
            return this.dispatchedToWorkshopField;
        }
        set
        {
            this.dispatchedToWorkshopField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum NewLabelsDispatchedToWorkshop
{
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    AfterUnloading,
    
    /// <remarks/>
    BeforeUnloading,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class DamageDescription
{
    
    private string remarksField;
    
    private Damage[] damageField;
    
    private DamageDescriptionCategory categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Remarks
    {
        get
        {
            return this.remarksField;
        }
        set
        {
            this.remarksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Damage", Order=1)]
    public Damage[] Damage
    {
        get
        {
            return this.damageField;
        }
        set
        {
            this.damageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DamageDescriptionCategory Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class Damage
{
    
    private string codeDigit1Field;
    
    private string codeDigit2Field;
    
    private string codeDigit3Field;
    
    private string codeDigit4Field;
    
    private bool oldDamageField;
    
    private bool oldDamageFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
    public string CodeDigit1
    {
        get
        {
            return this.codeDigit1Field;
        }
        set
        {
            this.codeDigit1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
    public string CodeDigit2
    {
        get
        {
            return this.codeDigit2Field;
        }
        set
        {
            this.codeDigit2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
    public string CodeDigit3
    {
        get
        {
            return this.codeDigit3Field;
        }
        set
        {
            this.codeDigit3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
    public string CodeDigit4
    {
        get
        {
            return this.codeDigit4Field;
        }
        set
        {
            this.codeDigit4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool OldDamage
    {
        get
        {
            return this.oldDamageField;
        }
        set
        {
            this.oldDamageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OldDamageSpecified
    {
        get
        {
            return this.oldDamageFieldSpecified;
        }
        set
        {
            this.oldDamageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class DamageDescriptionCategory
{
    
    private DamageDescriptionCategoryDamageCategory damageCategoryField;
    
    private DamageDescriptionCategoryPerpetrator perpetratorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public DamageDescriptionCategoryDamageCategory DamageCategory
    {
        get
        {
            return this.damageCategoryField;
        }
        set
        {
            this.damageCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public DamageDescriptionCategoryPerpetrator Perpetrator
    {
        get
        {
            return this.perpetratorField;
        }
        set
        {
            this.perpetratorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public enum DamageDescriptionCategoryDamageCategory
{
    
    /// <remarks/>
    Wear,
    
    /// <remarks/>
    ImpactDamage,
    
    /// <remarks/>
    ThirdParty,
    
    /// <remarks/>
    NotAscertainable,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class DamageDescriptionCategoryPerpetrator
{
    
    private AddressInformation addressInformationField;
    
    private AdministrativeContactInformation administrativeContactInformationField;
    
    private string remarksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AddressInformation AddressInformation
    {
        get
        {
            return this.addressInformationField;
        }
        set
        {
            this.addressInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public AdministrativeContactInformation AdministrativeContactInformation
    {
        get
        {
            return this.administrativeContactInformationField;
        }
        set
        {
            this.administrativeContactInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Remarks
    {
        get
        {
            return this.remarksField;
        }
        set
        {
            this.remarksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class Identifiers
{
    
    private CompositIdentifierPlannedType[] plannedTransportIdentifiersField;
    
    private CompositIdentifierPlannedType[] relatedPlannedTransportIdentifiersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PlannedTransportIdentifiers", Order=0)]
    public CompositIdentifierPlannedType[] PlannedTransportIdentifiers
    {
        get
        {
            return this.plannedTransportIdentifiersField;
        }
        set
        {
            this.plannedTransportIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelatedPlannedTransportIdentifiers", Order=1)]
    public CompositIdentifierPlannedType[] RelatedPlannedTransportIdentifiers
    {
        get
        {
            return this.relatedPlannedTransportIdentifiersField;
        }
        set
        {
            this.relatedPlannedTransportIdentifiersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/wdr")]
public enum TypeOfInformationCode
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("30")]
    Item30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("31")]
    Item31,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("40")]
    Item40,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("50")]
    Item50,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("51")]
    Item51,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("52")]
    Item52,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class AffectedSection
{
    
    private AffectedSectionStartOfSection startOfSectionField;
    
    private AffectedSectionEndOfSection endOfSectionField;
    
    private string operationalTrainNumberField;
    
    private PlannedCalendar plannedCalendarField;
    
    private NetworkSpecificParameter[] networkSpecificParameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AffectedSectionStartOfSection StartOfSection
    {
        get
        {
            return this.startOfSectionField;
        }
        set
        {
            this.startOfSectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public AffectedSectionEndOfSection EndOfSection
    {
        get
        {
            return this.endOfSectionField;
        }
        set
        {
            this.endOfSectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string OperationalTrainNumber
    {
        get
        {
            return this.operationalTrainNumberField;
        }
        set
        {
            this.operationalTrainNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public PlannedCalendar PlannedCalendar
    {
        get
        {
            return this.plannedCalendarField;
        }
        set
        {
            this.plannedCalendarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NetworkSpecificParameter", Order=4)]
    public NetworkSpecificParameter[] NetworkSpecificParameter
    {
        get
        {
            return this.networkSpecificParameterField;
        }
        set
        {
            this.networkSpecificParameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class AffectedSectionStartOfSection : LocationIdent
{
    
    private System.DateTime bookedLocationDateTimeField;
    
    private bool bookedLocationDateTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime BookedLocationDateTime
    {
        get
        {
            return this.bookedLocationDateTimeField;
        }
        set
        {
            this.bookedLocationDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BookedLocationDateTimeSpecified
    {
        get
        {
            return this.bookedLocationDateTimeFieldSpecified;
        }
        set
        {
            this.bookedLocationDateTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class AffectedSectionEndOfSection : LocationIdent
{
    
    private System.DateTime bookedLocationDateTimeField;
    
    private bool bookedLocationDateTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime BookedLocationDateTime
    {
        get
        {
            return this.bookedLocationDateTimeField;
        }
        set
        {
            this.bookedLocationDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BookedLocationDateTimeSpecified
    {
        get
        {
            return this.bookedLocationDateTimeFieldSpecified;
        }
        set
        {
            this.bookedLocationDateTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class PlannedCalendar
{
    
    private string bitmapDaysField;
    
    private ValidityPeriod validityPeriodField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string BitmapDays
    {
        get
        {
            return this.bitmapDaysField;
        }
        set
        {
            this.bitmapDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ValidityPeriod ValidityPeriod
    {
        get
        {
            return this.validityPeriodField;
        }
        set
        {
            this.validityPeriodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class ValidityPeriod
{
    
    private System.DateTime startDateTimeField;
    
    private System.DateTime endDateTimeField;
    
    private bool endDateTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime StartDateTime
    {
        get
        {
            return this.startDateTimeField;
        }
        set
        {
            this.startDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime EndDateTime
    {
        get
        {
            return this.endDateTimeField;
        }
        set
        {
            this.endDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateTimeSpecified
    {
        get
        {
            return this.endDateTimeFieldSpecified;
        }
        set
        {
            this.endDateTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class NetworkSpecificParameter
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/wdr")]
public partial class RelatedReference
{
    
    private string relatedTypeField;
    
    private string relatedIdentifierField;
    
    private System.DateTime relatedMessageDateTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string RelatedType
    {
        get
        {
            return this.relatedTypeField;
        }
        set
        {
            this.relatedTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string RelatedIdentifier
    {
        get
        {
            return this.relatedIdentifierField;
        }
        set
        {
            this.relatedIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime RelatedMessageDateTime
    {
        get
        {
            return this.relatedMessageDateTimeField;
        }
        set
        {
            this.relatedMessageDateTimeField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.MessageContractAttribute(WrapperName="WagonDamageReportMessage", WrapperNamespace="http://gcubroker.org/wdr", IsWrapped=true)]
public partial class wdrRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=0)]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=1)]
    public string ReportID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=2)]
    public string UserRU;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=3)]
    public WagonDamageReportMessageContactUserRU ContactUserRU;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=4)]
    public string Keeper;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=5)]
    public string WagonNumberFreight;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=6)]
    public TransportInformation TransportInformation;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=7)]
    public DamageDetection DamageDetection;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=8)]
    public ExistingLabels ExistingLabels;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=9)]
    public NewLabels NewLabels;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=10)]
    public DamageDescription DamageDescription;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=11)]
    public bool Attachments;
    
    public wdrRequest()
    {
    }
    
    public wdrRequest(MessageHeader MessageHeader, string ReportID, string UserRU, WagonDamageReportMessageContactUserRU ContactUserRU, string Keeper, string WagonNumberFreight, TransportInformation TransportInformation, DamageDetection DamageDetection, ExistingLabels ExistingLabels, NewLabels NewLabels, DamageDescription DamageDescription, bool Attachments)
    {
        this.MessageHeader = MessageHeader;
        this.ReportID = ReportID;
        this.UserRU = UserRU;
        this.ContactUserRU = ContactUserRU;
        this.Keeper = Keeper;
        this.WagonNumberFreight = WagonNumberFreight;
        this.TransportInformation = TransportInformation;
        this.DamageDetection = DamageDetection;
        this.ExistingLabels = ExistingLabels;
        this.NewLabels = NewLabels;
        this.DamageDescription = DamageDescription;
        this.Attachments = Attachments;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReceiptConfirmationMessage", WrapperNamespace="http://gcubroker.org/wdr", IsWrapped=true)]
public partial class wdrResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=0)]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=1)]
    public Identifiers Identifiers;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=2)]
    public short TypeOfRequest;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=3)]
    public TypeOfInformationCode TypeOfInformation;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("AffectedSection")]
    public AffectedSection[] AffectedSection;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/wdr", Order=5)]
    public RelatedReference RelatedReference;
    
    public wdrResponse()
    {
    }
    
    public wdrResponse(MessageHeader MessageHeader, Identifiers Identifiers, short TypeOfRequest, TypeOfInformationCode TypeOfInformation, AffectedSection[] AffectedSection, RelatedReference RelatedReference)
    {
        this.MessageHeader = MessageHeader;
        this.Identifiers = Identifiers;
        this.TypeOfRequest = TypeOfRequest;
        this.TypeOfInformation = TypeOfInformation;
        this.AffectedSection = AffectedSection;
        this.RelatedReference = RelatedReference;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public interface WdrEndpointChannel : WdrEndpoint, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public partial class WdrEndpointClient : System.ServiceModel.ClientBase<WdrEndpoint>, WdrEndpoint
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public WdrEndpointClient() : 
            base(WdrEndpointClient.GetDefaultBinding(), WdrEndpointClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.WdrService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WdrEndpointClient(EndpointConfiguration endpointConfiguration) : 
            base(WdrEndpointClient.GetBindingForEndpoint(endpointConfiguration), WdrEndpointClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WdrEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(WdrEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WdrEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(WdrEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WdrEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<wdrResponse> wdrAsync(wdrRequest request)
    {
        return base.Channel.wdrAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.WdrService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.WdrService))
        {
            return new System.ServiceModel.EndpointAddress("https://prod.gcubroker.org/wdr");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return WdrEndpointClient.GetBindingForEndpoint(EndpointConfiguration.WdrService);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return WdrEndpointClient.GetEndpointAddress(EndpointConfiguration.WdrService);
    }
    
    public enum EndpointConfiguration
    {
        
        WdrService,
    }
}
