//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class ErrorMessage
{
    
    private MessageHeader messageHeaderField;
    
    private MessageStatus messageStatusField;
    
    private AdministrativeContactInformation administrativeContactInformationField;
    
    private ErrorMessageErrorCauseReference errorCauseReferenceField;
    
    private ErrorMessageError[] errorField;
    
    private CompositIdentifierPlannedType[] plannedTransportIdentifiersField;
    
    private TransportOperationalIdentifiers[] transportOperationalIdentifiersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MessageHeader MessageHeader
    {
        get
        {
            return this.messageHeaderField;
        }
        set
        {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public MessageStatus MessageStatus
    {
        get
        {
            return this.messageStatusField;
        }
        set
        {
            this.messageStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public AdministrativeContactInformation AdministrativeContactInformation
    {
        get
        {
            return this.administrativeContactInformationField;
        }
        set
        {
            this.administrativeContactInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public ErrorMessageErrorCauseReference ErrorCauseReference
    {
        get
        {
            return this.errorCauseReferenceField;
        }
        set
        {
            this.errorCauseReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Error", Order=4)]
    public ErrorMessageError[] Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PlannedTransportIdentifiers", Order=5)]
    public CompositIdentifierPlannedType[] PlannedTransportIdentifiers
    {
        get
        {
            return this.plannedTransportIdentifiersField;
        }
        set
        {
            this.plannedTransportIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TransportOperationalIdentifiers", Order=6)]
    public TransportOperationalIdentifiers[] TransportOperationalIdentifiers
    {
        get
        {
            return this.transportOperationalIdentifiersField;
        }
        set
        {
            this.transportOperationalIdentifiersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class MessageHeader
{
    
    private MessageReference messageReferenceField;
    
    private string messageRoutingIDField;
    
    private string senderReferenceField;
    
    private Sender senderField;
    
    private Recipient recipientField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MessageReference MessageReference
    {
        get
        {
            return this.messageReferenceField;
        }
        set
        {
            this.messageReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string MessageRoutingID
    {
        get
        {
            return this.messageRoutingIDField;
        }
        set
        {
            this.messageRoutingIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SenderReference
    {
        get
        {
            return this.senderReferenceField;
        }
        set
        {
            this.senderReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public Sender Sender
    {
        get
        {
            return this.senderField;
        }
        set
        {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public Recipient Recipient
    {
        get
        {
            return this.recipientField;
        }
        set
        {
            this.recipientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class MessageReference
{
    
    private string messageTypeField;
    
    private string messageTypeVersionField;
    
    private string messageIdentifierField;
    
    private System.DateTime messageDateTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
    public string MessageType
    {
        get
        {
            return this.messageTypeField;
        }
        set
        {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MessageTypeVersion
    {
        get
        {
            return this.messageTypeVersionField;
        }
        set
        {
            this.messageTypeVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string MessageIdentifier
    {
        get
        {
            return this.messageIdentifierField;
        }
        set
        {
            this.messageIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime MessageDateTime
    {
        get
        {
            return this.messageDateTimeField;
        }
        set
        {
            this.messageDateTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/rsds")]
public partial class CompositIdentifierOperationalType
{
    
    private ObjectType objectTypeField;
    
    private string companyField;
    
    private string coreField;
    
    private string variantField;
    
    private string timetableYearField;
    
    private System.DateTime startDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ObjectType ObjectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Core
    {
        get
        {
            return this.coreField;
        }
        set
        {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Variant
    {
        get
        {
            return this.variantField;
        }
        set
        {
            this.variantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string TimetableYear
    {
        get
        {
            return this.timetableYearField;
        }
        set
        {
            this.timetableYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum ObjectType
{
    
    /// <remarks/>
    TR,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    CR,
    
    /// <remarks/>
    PR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/rsds")]
public partial class CompositIdentifierPlannedType
{
    
    private ObjectType objectTypeField;
    
    private string companyField;
    
    private string coreField;
    
    private string variantField;
    
    private string timetableYearField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ObjectType ObjectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Core
    {
        get
        {
            return this.coreField;
        }
        set
        {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Variant
    {
        get
        {
            return this.variantField;
        }
        set
        {
            this.variantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string TimetableYear
    {
        get
        {
            return this.timetableYearField;
        }
        set
        {
            this.timetableYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
    public System.DateTime StartDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartDateSpecified
    {
        get
        {
            return this.startDateFieldSpecified;
        }
        set
        {
            this.startDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class Sender
{
    
    private string cI_InstanceNumberField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="integer")]
    public string CI_InstanceNumber
    {
        get
        {
            return this.cI_InstanceNumberField;
        }
        set
        {
            this.cI_InstanceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class Recipient
{
    
    private string cI_InstanceNumberField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="integer")]
    public string CI_InstanceNumber
    {
        get
        {
            return this.cI_InstanceNumberField;
        }
        set
        {
            this.cI_InstanceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum MessageStatus
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class AdministrativeContactInformation
{
    
    private string nameField;
    
    private string eMailField;
    
    private string phoneNumberField;
    
    private string faxNumberField;
    
    private string freeTextFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string eMail
    {
        get
        {
            return this.eMailField;
        }
        set
        {
            this.eMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string PhoneNumber
    {
        get
        {
            return this.phoneNumberField;
        }
        set
        {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string FaxNumber
    {
        get
        {
            return this.faxNumberField;
        }
        set
        {
            this.faxNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string FreeTextField
    {
        get
        {
            return this.freeTextFieldField;
        }
        set
        {
            this.freeTextFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class ErrorMessageErrorCauseReference
{
    
    private MessageReference messageReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MessageReference MessageReference
    {
        get
        {
            return this.messageReferenceField;
        }
        set
        {
            this.messageReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class ErrorMessageError
{
    
    private string tagReferenceField;
    
    private ErrorMessageErrorTypeOfError typeOfErrorField;
    
    private ErrorMessageErrorSeverity severityField;
    
    private string errorCodeField;
    
    private string freeTextFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string TagReference
    {
        get
        {
            return this.tagReferenceField;
        }
        set
        {
            this.tagReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ErrorMessageErrorTypeOfError TypeOfError
    {
        get
        {
            return this.typeOfErrorField;
        }
        set
        {
            this.typeOfErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ErrorMessageErrorSeverity Severity
    {
        get
        {
            return this.severityField;
        }
        set
        {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string FreeTextField
    {
        get
        {
            return this.freeTextFieldField;
        }
        set
        {
            this.freeTextFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum ErrorMessageErrorTypeOfError
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum ErrorMessageErrorSeverity
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class TransportOperationalIdentifiers : CompositIdentifierOperationalType
{
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://gcubroker.org/rsds", ConfigurationName="RsdsEndpoint")]
public interface RsdsEndpoint
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://gcubroker.org/rsds", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(ErrorMessage), Action="http://gcubroker.org/rsds", Name="ErrorMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CompositIdentifierOperationalType))]
    System.Threading.Tasks.Task<rsdsResponse> rsdsAsync(rsdsRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDataset
{
    
    private RollingStockDatasetAdministrativeDataSet administrativeDataSetField;
    
    private RollingStockDatasetDesignDataSet designDataSetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RollingStockDatasetAdministrativeDataSet AdministrativeDataSet
    {
        get
        {
            return this.administrativeDataSetField;
        }
        set
        {
            this.administrativeDataSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RollingStockDatasetDesignDataSet DesignDataSet
    {
        get
        {
            return this.designDataSetField;
        }
        set
        {
            this.designDataSetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetAdministrativeDataSet
{
    
    private string wagonNumberFreightField;
    
    private string previousWagonNumberFreightField;
    
    private string registrationCountryField;
    
    private System.DateTime datePutIntoServiceField;
    
    private System.DateTime authorisationValidUntilField;
    
    private bool authorisationValidUntilFieldSpecified;
    
    private bool suspensionOfAuthorisationField;
    
    private System.DateTime dateSuspensionOfAuthorisationField;
    
    private bool dateSuspensionOfAuthorisationFieldSpecified;
    
    private string[] multilateralAuthorisationCountriesField;
    
    private bool channelTunnelPermittedField;
    
    private bool channelTunnelPermittedFieldSpecified;
    
    private string keeperShortNameVKMField;
    
    private string eCMField;
    
    private RollingStockDatasetAdministrativeDataSetPlannedChangeOfECM plannedChangeOfECMField;
    
    private RollingStockDatasetAdministrativeDataSetECMCertificate eCMCertificateField;
    
    private InteropCapability interopCapabilityField;
    
    private bool gCUWagonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string WagonNumberFreight
    {
        get
        {
            return this.wagonNumberFreightField;
        }
        set
        {
            this.wagonNumberFreightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string PreviousWagonNumberFreight
    {
        get
        {
            return this.previousWagonNumberFreightField;
        }
        set
        {
            this.previousWagonNumberFreightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string RegistrationCountry
    {
        get
        {
            return this.registrationCountryField;
        }
        set
        {
            this.registrationCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
    public System.DateTime DatePutIntoService
    {
        get
        {
            return this.datePutIntoServiceField;
        }
        set
        {
            this.datePutIntoServiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
    public System.DateTime AuthorisationValidUntil
    {
        get
        {
            return this.authorisationValidUntilField;
        }
        set
        {
            this.authorisationValidUntilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AuthorisationValidUntilSpecified
    {
        get
        {
            return this.authorisationValidUntilFieldSpecified;
        }
        set
        {
            this.authorisationValidUntilFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public bool SuspensionOfAuthorisation
    {
        get
        {
            return this.suspensionOfAuthorisationField;
        }
        set
        {
            this.suspensionOfAuthorisationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
    public System.DateTime DateSuspensionOfAuthorisation
    {
        get
        {
            return this.dateSuspensionOfAuthorisationField;
        }
        set
        {
            this.dateSuspensionOfAuthorisationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateSuspensionOfAuthorisationSpecified
    {
        get
        {
            return this.dateSuspensionOfAuthorisationFieldSpecified;
        }
        set
        {
            this.dateSuspensionOfAuthorisationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MultilateralAuthorisationCountries", Order=7)]
    public string[] MultilateralAuthorisationCountries
    {
        get
        {
            return this.multilateralAuthorisationCountriesField;
        }
        set
        {
            this.multilateralAuthorisationCountriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public bool ChannelTunnelPermitted
    {
        get
        {
            return this.channelTunnelPermittedField;
        }
        set
        {
            this.channelTunnelPermittedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChannelTunnelPermittedSpecified
    {
        get
        {
            return this.channelTunnelPermittedFieldSpecified;
        }
        set
        {
            this.channelTunnelPermittedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string KeeperShortNameVKM
    {
        get
        {
            return this.keeperShortNameVKMField;
        }
        set
        {
            this.keeperShortNameVKMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string ECM
    {
        get
        {
            return this.eCMField;
        }
        set
        {
            this.eCMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public RollingStockDatasetAdministrativeDataSetPlannedChangeOfECM PlannedChangeOfECM
    {
        get
        {
            return this.plannedChangeOfECMField;
        }
        set
        {
            this.plannedChangeOfECMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public RollingStockDatasetAdministrativeDataSetECMCertificate ECMCertificate
    {
        get
        {
            return this.eCMCertificateField;
        }
        set
        {
            this.eCMCertificateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public InteropCapability InteropCapability
    {
        get
        {
            return this.interopCapabilityField;
        }
        set
        {
            this.interopCapabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public bool GCUWagon
    {
        get
        {
            return this.gCUWagonField;
        }
        set
        {
            this.gCUWagonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetAdministrativeDataSetPlannedChangeOfECM
{
    
    private System.DateTime currentECMAssignedUntilField;
    
    private string subsequentECMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
    public System.DateTime CurrentECMAssignedUntil
    {
        get
        {
            return this.currentECMAssignedUntilField;
        }
        set
        {
            this.currentECMAssignedUntilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string SubsequentECM
    {
        get
        {
            return this.subsequentECMField;
        }
        set
        {
            this.subsequentECMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetAdministrativeDataSetECMCertificate
{
    
    private RollingStockDatasetAdministrativeDataSetECMCertificateEINNumber eINNumberField;
    
    private System.DateTime eCMCertificateValidFromField;
    
    private System.DateTime eCMCertificateValidToField;
    
    private bool coversTankWagonsForDangerousGoodsField;
    
    private bool coversNonTankWagonsForDangerousGoodsField;
    
    private bool eCMCertificateSuspendedField;
    
    private System.DateTime dateECMCertificateSuspendedField;
    
    private bool dateECMCertificateSuspendedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RollingStockDatasetAdministrativeDataSetECMCertificateEINNumber EINNumber
    {
        get
        {
            return this.eINNumberField;
        }
        set
        {
            this.eINNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
    public System.DateTime ECMCertificateValidFrom
    {
        get
        {
            return this.eCMCertificateValidFromField;
        }
        set
        {
            this.eCMCertificateValidFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
    public System.DateTime ECMCertificateValidTo
    {
        get
        {
            return this.eCMCertificateValidToField;
        }
        set
        {
            this.eCMCertificateValidToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public bool CoversTankWagonsForDangerousGoods
    {
        get
        {
            return this.coversTankWagonsForDangerousGoodsField;
        }
        set
        {
            this.coversTankWagonsForDangerousGoodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool CoversNonTankWagonsForDangerousGoods
    {
        get
        {
            return this.coversNonTankWagonsForDangerousGoodsField;
        }
        set
        {
            this.coversNonTankWagonsForDangerousGoodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public bool ECMCertificateSuspended
    {
        get
        {
            return this.eCMCertificateSuspendedField;
        }
        set
        {
            this.eCMCertificateSuspendedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
    public System.DateTime DateECMCertificateSuspended
    {
        get
        {
            return this.dateECMCertificateSuspendedField;
        }
        set
        {
            this.dateECMCertificateSuspendedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateECMCertificateSuspendedSpecified
    {
        get
        {
            return this.dateECMCertificateSuspendedFieldSpecified;
        }
        set
        {
            this.dateECMCertificateSuspendedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetAdministrativeDataSetECMCertificateEINNumber
{
    
    private CountryCodeISO countryCodeISOField;
    
    private string typeDocumentEINField;
    
    private string counterAcreditedRecognizedBodyField;
    
    private string eINYearField;
    
    private string eINCounterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public CountryCodeISO CountryCodeISO
    {
        get
        {
            return this.countryCodeISOField;
        }
        set
        {
            this.countryCodeISOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string TypeDocumentEIN
    {
        get
        {
            return this.typeDocumentEINField;
        }
        set
        {
            this.typeDocumentEINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
    public string CounterAcreditedRecognizedBody
    {
        get
        {
            return this.counterAcreditedRecognizedBodyField;
        }
        set
        {
            this.counterAcreditedRecognizedBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
    public string EINYear
    {
        get
        {
            return this.eINYearField;
        }
        set
        {
            this.eINYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string EINCounter
    {
        get
        {
            return this.eINCounterField;
        }
        set
        {
            this.eINCounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class CountryCodeISO
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum InteropCapability
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSet
{
    
    private string letterMarkingField;
    
    private string tankCodeField;
    
    private int wagonNumberOfAxlesField;
    
    private string wheelSetTypeField;
    
    private string wheelDiameterField;
    
    private string[] wheelsetGaugeField;
    
    private WheelSetTransformationMethod wheelSetTransformationMethodField;
    
    private bool wheelSetTransformationMethodFieldSpecified;
    
    private int numberOfBogiesField;
    
    private bool numberOfBogiesFieldSpecified;
    
    private string bogiePitchField;
    
    private string bogiePivotPitchField;
    
    private string innerWheelbaseField;
    
    private CouplingType couplingTypeField;
    
    private bool couplingTypeFieldSpecified;
    
    private string bufferTypeField;
    
    private NormalLoadingGauge normalLoadingGaugeField;
    
    private bool normalLoadingGaugeFieldSpecified;
    
    private string minCurveRadiusField;
    
    private string minVerticalRadiusYardHumpField;
    
    private string wagonWeightEmptyField;
    
    private string lengthOverBuffersField;
    
    private decimal maxAxleWeightField;
    
    private RollingStockDatasetDesignDataSetLoadTable[] loadTableField;
    
    private string maxDesignSpeedField;
    
    private AirBrake airBrakeField;
    
    private HandBrake handBrakeField;
    
    private RollingStockDatasetDesignDataSetBrakeBlock brakeBlockField;
    
    private string maxLengthOfLoadField;
    
    private decimal loadAreaField;
    
    private bool loadAreaFieldSpecified;
    
    private string heightOfLoadingPlaneUnladenField;
    
    private RollingStockDatasetDesignDataSetRemovableAccessories[] removableAccessoriesField;
    
    private decimal loadingCapacityField;
    
    private bool loadingCapacityFieldSpecified;
    
    private string maxGrossWeightField;
    
    private bool vapourReturnSystemField;
    
    private bool vapourReturnSystemFieldSpecified;
    
    private bool ferryPermittedFlagField;
    
    private bool ferryPermittedFlagFieldSpecified;
    
    private decimal ferryRampAngleField;
    
    private bool ferryRampAngleFieldSpecified;
    
    private RollingStockDatasetDesignDataSetTemperatureRange temperatureRangeField;
    
    private string noiseByPassLimitField;
    
    private string noiseField;
    
    private RestrictionCodes[] technicalForwardingRestrictionsField;
    
    private System.DateTime dateLastOverhaulField;
    
    private System.DateTime dateNextOverhaulField;
    
    private string permittedToleranceField;
    
    private System.DateTime dateOfNextTankInspectionField;
    
    private bool dateOfNextTankInspectionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string LetterMarking
    {
        get
        {
            return this.letterMarkingField;
        }
        set
        {
            this.letterMarkingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TankCode
    {
        get
        {
            return this.tankCodeField;
        }
        set
        {
            this.tankCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int WagonNumberOfAxles
    {
        get
        {
            return this.wagonNumberOfAxlesField;
        }
        set
        {
            this.wagonNumberOfAxlesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string WheelSetType
    {
        get
        {
            return this.wheelSetTypeField;
        }
        set
        {
            this.wheelSetTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string WheelDiameter
    {
        get
        {
            return this.wheelDiameterField;
        }
        set
        {
            this.wheelDiameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WheelsetGauge", DataType="integer", Order=5)]
    public string[] WheelsetGauge
    {
        get
        {
            return this.wheelsetGaugeField;
        }
        set
        {
            this.wheelsetGaugeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public WheelSetTransformationMethod WheelSetTransformationMethod
    {
        get
        {
            return this.wheelSetTransformationMethodField;
        }
        set
        {
            this.wheelSetTransformationMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WheelSetTransformationMethodSpecified
    {
        get
        {
            return this.wheelSetTransformationMethodFieldSpecified;
        }
        set
        {
            this.wheelSetTransformationMethodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public int NumberOfBogies
    {
        get
        {
            return this.numberOfBogiesField;
        }
        set
        {
            this.numberOfBogiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberOfBogiesSpecified
    {
        get
        {
            return this.numberOfBogiesFieldSpecified;
        }
        set
        {
            this.numberOfBogiesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=8)]
    public string BogiePitch
    {
        get
        {
            return this.bogiePitchField;
        }
        set
        {
            this.bogiePitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=9)]
    public string BogiePivotPitch
    {
        get
        {
            return this.bogiePivotPitchField;
        }
        set
        {
            this.bogiePivotPitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=10)]
    public string InnerWheelbase
    {
        get
        {
            return this.innerWheelbaseField;
        }
        set
        {
            this.innerWheelbaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public CouplingType CouplingType
    {
        get
        {
            return this.couplingTypeField;
        }
        set
        {
            this.couplingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CouplingTypeSpecified
    {
        get
        {
            return this.couplingTypeFieldSpecified;
        }
        set
        {
            this.couplingTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public string BufferType
    {
        get
        {
            return this.bufferTypeField;
        }
        set
        {
            this.bufferTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public NormalLoadingGauge NormalLoadingGauge
    {
        get
        {
            return this.normalLoadingGaugeField;
        }
        set
        {
            this.normalLoadingGaugeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NormalLoadingGaugeSpecified
    {
        get
        {
            return this.normalLoadingGaugeFieldSpecified;
        }
        set
        {
            this.normalLoadingGaugeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=14)]
    public string MinCurveRadius
    {
        get
        {
            return this.minCurveRadiusField;
        }
        set
        {
            this.minCurveRadiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=15)]
    public string MinVerticalRadiusYardHump
    {
        get
        {
            return this.minVerticalRadiusYardHumpField;
        }
        set
        {
            this.minVerticalRadiusYardHumpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=16)]
    public string WagonWeightEmpty
    {
        get
        {
            return this.wagonWeightEmptyField;
        }
        set
        {
            this.wagonWeightEmptyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=17)]
    public string LengthOverBuffers
    {
        get
        {
            return this.lengthOverBuffersField;
        }
        set
        {
            this.lengthOverBuffersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public decimal MaxAxleWeight
    {
        get
        {
            return this.maxAxleWeightField;
        }
        set
        {
            this.maxAxleWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LoadTable", Order=19)]
    public RollingStockDatasetDesignDataSetLoadTable[] LoadTable
    {
        get
        {
            return this.loadTableField;
        }
        set
        {
            this.loadTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=20)]
    public string MaxDesignSpeed
    {
        get
        {
            return this.maxDesignSpeedField;
        }
        set
        {
            this.maxDesignSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public AirBrake AirBrake
    {
        get
        {
            return this.airBrakeField;
        }
        set
        {
            this.airBrakeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public HandBrake HandBrake
    {
        get
        {
            return this.handBrakeField;
        }
        set
        {
            this.handBrakeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public RollingStockDatasetDesignDataSetBrakeBlock BrakeBlock
    {
        get
        {
            return this.brakeBlockField;
        }
        set
        {
            this.brakeBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=24)]
    public string MaxLengthOfLoad
    {
        get
        {
            return this.maxLengthOfLoadField;
        }
        set
        {
            this.maxLengthOfLoadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public decimal LoadArea
    {
        get
        {
            return this.loadAreaField;
        }
        set
        {
            this.loadAreaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadAreaSpecified
    {
        get
        {
            return this.loadAreaFieldSpecified;
        }
        set
        {
            this.loadAreaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=26)]
    public string HeightOfLoadingPlaneUnladen
    {
        get
        {
            return this.heightOfLoadingPlaneUnladenField;
        }
        set
        {
            this.heightOfLoadingPlaneUnladenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RemovableAccessories", Order=27)]
    public RollingStockDatasetDesignDataSetRemovableAccessories[] RemovableAccessories
    {
        get
        {
            return this.removableAccessoriesField;
        }
        set
        {
            this.removableAccessoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=28)]
    public decimal LoadingCapacity
    {
        get
        {
            return this.loadingCapacityField;
        }
        set
        {
            this.loadingCapacityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadingCapacitySpecified
    {
        get
        {
            return this.loadingCapacityFieldSpecified;
        }
        set
        {
            this.loadingCapacityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=29)]
    public string MaxGrossWeight
    {
        get
        {
            return this.maxGrossWeightField;
        }
        set
        {
            this.maxGrossWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=30)]
    public bool VapourReturnSystem
    {
        get
        {
            return this.vapourReturnSystemField;
        }
        set
        {
            this.vapourReturnSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VapourReturnSystemSpecified
    {
        get
        {
            return this.vapourReturnSystemFieldSpecified;
        }
        set
        {
            this.vapourReturnSystemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=31)]
    public bool FerryPermittedFlag
    {
        get
        {
            return this.ferryPermittedFlagField;
        }
        set
        {
            this.ferryPermittedFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FerryPermittedFlagSpecified
    {
        get
        {
            return this.ferryPermittedFlagFieldSpecified;
        }
        set
        {
            this.ferryPermittedFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=32)]
    public decimal FerryRampAngle
    {
        get
        {
            return this.ferryRampAngleField;
        }
        set
        {
            this.ferryRampAngleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FerryRampAngleSpecified
    {
        get
        {
            return this.ferryRampAngleFieldSpecified;
        }
        set
        {
            this.ferryRampAngleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=33)]
    public RollingStockDatasetDesignDataSetTemperatureRange TemperatureRange
    {
        get
        {
            return this.temperatureRangeField;
        }
        set
        {
            this.temperatureRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=34)]
    public string NoiseByPassLimit
    {
        get
        {
            return this.noiseByPassLimitField;
        }
        set
        {
            this.noiseByPassLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=35)]
    public string Noise
    {
        get
        {
            return this.noiseField;
        }
        set
        {
            this.noiseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TechnicalForwardingRestrictions", Order=36)]
    public RestrictionCodes[] TechnicalForwardingRestrictions
    {
        get
        {
            return this.technicalForwardingRestrictionsField;
        }
        set
        {
            this.technicalForwardingRestrictionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=37)]
    public System.DateTime DateLastOverhaul
    {
        get
        {
            return this.dateLastOverhaulField;
        }
        set
        {
            this.dateLastOverhaulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=38)]
    public System.DateTime DateNextOverhaul
    {
        get
        {
            return this.dateNextOverhaulField;
        }
        set
        {
            this.dateNextOverhaulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=39)]
    public string PermittedTolerance
    {
        get
        {
            return this.permittedToleranceField;
        }
        set
        {
            this.permittedToleranceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=40)]
    public System.DateTime DateOfNextTankInspection
    {
        get
        {
            return this.dateOfNextTankInspectionField;
        }
        set
        {
            this.dateOfNextTankInspectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateOfNextTankInspectionSpecified
    {
        get
        {
            return this.dateOfNextTankInspectionFieldSpecified;
        }
        set
        {
            this.dateOfNextTankInspectionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum WheelSetTransformationMethod
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum CouplingType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum NormalLoadingGauge
{
    
    /// <remarks/>
    G1,
    
    /// <remarks/>
    G2,
    
    /// <remarks/>
    GA,
    
    /// <remarks/>
    GB,
    
    /// <remarks/>
    GB1,
    
    /// <remarks/>
    GB2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("GB-M6")]
    GBM6,
    
    /// <remarks/>
    GHE16,
    
    /// <remarks/>
    GC,
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("W6-A")]
    W6A,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSetLoadTable
{
    
    private RollingStockDatasetDesignDataSetLoadTableLoadTableProduct loadTableProductField;
    
    private string[] loadTableCountryField;
    
    private string[] speedCategoryField;
    
    private LoadTableStars loadTableStarsField;
    
    private bool loadTableStarsFieldSpecified;
    
    private RollingStockDatasetDesignDataSetLoadTableRouteClassPayloads[] routeClassPayloadsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RollingStockDatasetDesignDataSetLoadTableLoadTableProduct LoadTableProduct
    {
        get
        {
            return this.loadTableProductField;
        }
        set
        {
            this.loadTableProductField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LoadTableCountry", Order=1)]
    public string[] LoadTableCountry
    {
        get
        {
            return this.loadTableCountryField;
        }
        set
        {
            this.loadTableCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpeedCategory", DataType="positiveInteger", Order=2)]
    public string[] SpeedCategory
    {
        get
        {
            return this.speedCategoryField;
        }
        set
        {
            this.speedCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public LoadTableStars LoadTableStars
    {
        get
        {
            return this.loadTableStarsField;
        }
        set
        {
            this.loadTableStarsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadTableStarsSpecified
    {
        get
        {
            return this.loadTableStarsFieldSpecified;
        }
        set
        {
            this.loadTableStarsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RouteClassPayloads", Order=4)]
    public RollingStockDatasetDesignDataSetLoadTableRouteClassPayloads[] RouteClassPayloads
    {
        get
        {
            return this.routeClassPayloadsField;
        }
        set
        {
            this.routeClassPayloadsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSetLoadTableLoadTableProduct
{
    
    private string productUNCodeField;
    
    private string productRIDNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
    public string ProductUNCode
    {
        get
        {
            return this.productUNCodeField;
        }
        set
        {
            this.productUNCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ProductRIDName
    {
        get
        {
            return this.productRIDNameField;
        }
        set
        {
            this.productRIDNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum LoadTableStars
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSetLoadTableRouteClassPayloads
{
    
    private RouteClass routeClassField;
    
    private decimal[] maxPayloadField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RouteClass RouteClass
    {
        get
        {
            return this.routeClassField;
        }
        set
        {
            this.routeClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MaxPayload", Order=1)]
    public decimal[] MaxPayload
    {
        get
        {
            return this.maxPayloadField;
        }
        set
        {
            this.maxPayloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum RouteClass
{
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    E,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    C2,
    
    /// <remarks/>
    C4,
    
    /// <remarks/>
    CM2,
    
    /// <remarks/>
    CM3,
    
    /// <remarks/>
    CM4,
    
    /// <remarks/>
    CM,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    D2,
    
    /// <remarks/>
    D4,
    
    /// <remarks/>
    A2,
    
    /// <remarks/>
    A4,
    
    /// <remarks/>
    B1,
    
    /// <remarks/>
    B2,
    
    /// <remarks/>
    C3,
    
    /// <remarks/>
    D3,
    
    /// <remarks/>
    E4,
    
    /// <remarks/>
    E5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class AirBrake
{
    
    private string numberOfBrakesField;
    
    private string brakeSystemField;
    
    private AirBrakeType airBrakeTypeField;
    
    private BrakingPowerVariationDevice brakingPowerVariationDeviceField;
    
    private string airBrakedMassField;
    
    private AirBrakeLoadChangeDevice[] loadChangeDeviceField;
    
    private BrakeSpecialCharacteristics brakeSpecialCharacteristicsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
    public string NumberOfBrakes
    {
        get
        {
            return this.numberOfBrakesField;
        }
        set
        {
            this.numberOfBrakesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string BrakeSystem
    {
        get
        {
            return this.brakeSystemField;
        }
        set
        {
            this.brakeSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public AirBrakeType AirBrakeType
    {
        get
        {
            return this.airBrakeTypeField;
        }
        set
        {
            this.airBrakeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public BrakingPowerVariationDevice BrakingPowerVariationDevice
    {
        get
        {
            return this.brakingPowerVariationDeviceField;
        }
        set
        {
            this.brakingPowerVariationDeviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string AirBrakedMass
    {
        get
        {
            return this.airBrakedMassField;
        }
        set
        {
            this.airBrakedMassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LoadChangeDevice", Order=5)]
    public AirBrakeLoadChangeDevice[] LoadChangeDevice
    {
        get
        {
            return this.loadChangeDeviceField;
        }
        set
        {
            this.loadChangeDeviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public BrakeSpecialCharacteristics BrakeSpecialCharacteristics
    {
        get
        {
            return this.brakeSpecialCharacteristicsField;
        }
        set
        {
            this.brakeSpecialCharacteristicsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum AirBrakeType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum BrakingPowerVariationDevice
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class AirBrakeLoadChangeDevice
{
    
    private string changeOverWeightField;
    
    private string airBrakedMassLoadedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
    public string ChangeOverWeight
    {
        get
        {
            return this.changeOverWeightField;
        }
        set
        {
            this.changeOverWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string AirBrakedMassLoaded
    {
        get
        {
            return this.airBrakedMassLoadedField;
        }
        set
        {
            this.airBrakedMassLoadedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum BrakeSpecialCharacteristics
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class HandBrake
{
    
    private HandBrakeType handBrakeTypeField;
    
    private decimal handBrakedWeightField;
    
    private bool handBrakedWeightFieldSpecified;
    
    private decimal parkingBrakeForceField;
    
    private bool parkingBrakeForceFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public HandBrakeType HandBrakeType
    {
        get
        {
            return this.handBrakeTypeField;
        }
        set
        {
            this.handBrakeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public decimal HandBrakedWeight
    {
        get
        {
            return this.handBrakedWeightField;
        }
        set
        {
            this.handBrakedWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HandBrakedWeightSpecified
    {
        get
        {
            return this.handBrakedWeightFieldSpecified;
        }
        set
        {
            this.handBrakedWeightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public decimal ParkingBrakeForce
    {
        get
        {
            return this.parkingBrakeForceField;
        }
        set
        {
            this.parkingBrakeForceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ParkingBrakeForceSpecified
    {
        get
        {
            return this.parkingBrakeForceFieldSpecified;
        }
        set
        {
            this.parkingBrakeForceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum HandBrakeType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSetBrakeBlock
{
    
    private string brakeBlockNameField;
    
    private bool compositeBrakeBlockRetrofittedField;
    
    private bool compositeBrakeBlockRetrofittedFieldSpecified;
    
    private System.DateTime compositeBrakeBlockInstallationDateField;
    
    private bool compositeBrakeBlockInstallationDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string BrakeBlockName
    {
        get
        {
            return this.brakeBlockNameField;
        }
        set
        {
            this.brakeBlockNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool CompositeBrakeBlockRetrofitted
    {
        get
        {
            return this.compositeBrakeBlockRetrofittedField;
        }
        set
        {
            this.compositeBrakeBlockRetrofittedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompositeBrakeBlockRetrofittedSpecified
    {
        get
        {
            return this.compositeBrakeBlockRetrofittedFieldSpecified;
        }
        set
        {
            this.compositeBrakeBlockRetrofittedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
    public System.DateTime CompositeBrakeBlockInstallationDate
    {
        get
        {
            return this.compositeBrakeBlockInstallationDateField;
        }
        set
        {
            this.compositeBrakeBlockInstallationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompositeBrakeBlockInstallationDateSpecified
    {
        get
        {
            return this.compositeBrakeBlockInstallationDateFieldSpecified;
        }
        set
        {
            this.compositeBrakeBlockInstallationDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSetRemovableAccessories
{
    
    private TypeOfRemovableAccessories typeOfRemovableAccessoriesField;
    
    private string numberOfAccessorOfSpecTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TypeOfRemovableAccessories TypeOfRemovableAccessories
    {
        get
        {
            return this.typeOfRemovableAccessoriesField;
        }
        set
        {
            this.typeOfRemovableAccessoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string NumberOfAccessorOfSpecType
    {
        get
        {
            return this.numberOfAccessorOfSpecTypeField;
        }
        set
        {
            this.numberOfAccessorOfSpecTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum TypeOfRemovableAccessories
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("01")]
    Item01,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("02")]
    Item02,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("03")]
    Item03,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("04")]
    Item04,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("05")]
    Item05,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("06")]
    Item06,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("07")]
    Item07,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("08")]
    Item08,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("09")]
    Item09,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("20")]
    Item20,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("26")]
    Item26,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("27")]
    Item27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("28")]
    Item28,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("29")]
    Item29,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetDesignDataSetTemperatureRange
{
    
    private int maxTempField;
    
    private int minTempField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int MaxTemp
    {
        get
        {
            return this.maxTempField;
        }
        set
        {
            this.maxTempField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int MinTemp
    {
        get
        {
            return this.minTempField;
        }
        set
        {
            this.minTempField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gcubroker.org/rsds")]
public enum RestrictionCodes
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("07")]
    Item07,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("08")]
    Item08,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("09")]
    Item09,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("30")]
    Item30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("31")]
    Item31,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("32")]
    Item32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("33")]
    Item33,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("34")]
    Item34,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("35")]
    Item35,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("36")]
    Item36,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("37")]
    Item37,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("38")]
    Item38,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("39")]
    Item39,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("41")]
    Item41,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("42")]
    Item42,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("50")]
    Item50,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("52")]
    Item52,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("62")]
    Item62,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("63")]
    Item63,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("68")]
    Item68,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("70")]
    Item70,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("71")]
    Item71,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("91")]
    Item91,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("92")]
    Item92,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("94")]
    Item94,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public partial class RollingStockDatasetMessageRefusedWagonNumbers
{
    
    private string wagonNumberFreightField;
    
    private RefusalCode refusalCodeField;
    
    private string keeperShortNameVKMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string WagonNumberFreight
    {
        get
        {
            return this.wagonNumberFreightField;
        }
        set
        {
            this.wagonNumberFreightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RefusalCode RefusalCode
    {
        get
        {
            return this.refusalCodeField;
        }
        set
        {
            this.refusalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string KeeperShortNameVKM
    {
        get
        {
            return this.keeperShortNameVKMField;
        }
        set
        {
            this.keeperShortNameVKMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gcubroker.org/rsds")]
public enum RefusalCode
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("101")]
    Item101,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("102")]
    Item102,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("103")]
    Item103,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("104")]
    Item104,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("105")]
    Item105,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("106")]
    Item106,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("107")]
    Item107,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("108")]
    Item108,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("109")]
    Item109,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("110")]
    Item110,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("111")]
    Item111,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("112")]
    Item112,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("113")]
    Item113,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("114")]
    Item114,
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RollingStockDatasetQueryMessage", WrapperNamespace="http://gcubroker.org/rsds", IsWrapped=true)]
public partial class rsdsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/rsds", Order=0)]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/rsds", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("WagonNumberFreight")]
    public string[] WagonNumberFreight;
    
    public rsdsRequest()
    {
    }
    
    public rsdsRequest(MessageHeader MessageHeader, string[] WagonNumberFreight)
    {
        this.MessageHeader = MessageHeader;
        this.WagonNumberFreight = WagonNumberFreight;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RollingStockDatasetMessage", WrapperNamespace="http://gcubroker.org/rsds", IsWrapped=true)]
public partial class rsdsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/rsds", Order=0)]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/rsds", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("RollingStockDataset")]
    public RollingStockDataset[] RollingStockDataset;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gcubroker.org/rsds", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("RefusedWagonNumbers")]
    public RollingStockDatasetMessageRefusedWagonNumbers[] RefusedWagonNumbers;
    
    public rsdsResponse()
    {
    }
    
    public rsdsResponse(MessageHeader MessageHeader, RollingStockDataset[] RollingStockDataset, RollingStockDatasetMessageRefusedWagonNumbers[] RefusedWagonNumbers)
    {
        this.MessageHeader = MessageHeader;
        this.RollingStockDataset = RollingStockDataset;
        this.RefusedWagonNumbers = RefusedWagonNumbers;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public interface RsdsEndpointChannel : RsdsEndpoint, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
public partial class RsdsEndpointClient : System.ServiceModel.ClientBase<RsdsEndpoint>, RsdsEndpoint
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public RsdsEndpointClient() : 
            base(RsdsEndpointClient.GetDefaultBinding(), RsdsEndpointClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.RsdsService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public RsdsEndpointClient(EndpointConfiguration endpointConfiguration) : 
            base(RsdsEndpointClient.GetBindingForEndpoint(endpointConfiguration), RsdsEndpointClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public RsdsEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(RsdsEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public RsdsEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(RsdsEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public RsdsEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<rsdsResponse> rsdsAsync(rsdsRequest request)
    {
        return base.Channel.rsdsAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.RsdsService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.RsdsService))
        {
            return new System.ServiceModel.EndpointAddress("http://prod.gcubroker.org/rsds");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return RsdsEndpointClient.GetBindingForEndpoint(EndpointConfiguration.RsdsService);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return RsdsEndpointClient.GetEndpointAddress(EndpointConfiguration.RsdsService);
    }
    
    public enum EndpointConfiguration
    {
        
        RsdsService,
    }
}
